<?php
include "IShopPage.php";
class RegPage extends ShopPage{
    public function __construct(string $title='')
    {
        $this->payload();
        $this->create_title($title);
        $this->create_body();
    }
    public function payload()
    {
        if(isset( $_COOKIE['warning']))
        {
            echo $_COOKIE['warning'];
            setcookie('warning',"");
        }
        echo '<!DOCTYPE html>
                <html lang="ru">';
    }
    public function end_body()
    {
        parent::end_body(); // TODO: Change the autogenerated stub
        echo '</html>';
    }
}
$PageController = new RegPage('Регистрация');
?>

<article>
<div class="title">
            <h2 class="font-effect-anaglyphic">Регистрация</h2>
        </div>
        <div class="catalog">
            <table>
                <form action="cab.php" method="post">
                    <tr><td class="reg">Имя</td><td class="reg"><input type="text" name="name"></td></tr>
                    <tr><td class="reg">Фамилия</td><td class="reg"><input type="text" name="surname"></td></tr>
                    <tr><td class="reg">Пароль</td><td class="reg"><input type="password" name="password"></td></tr>
                    <tr><td class="reg">Телефон</td><td class="reg"><input type="tel" name="phone"></td></tr>
                    <tr><td class="reg">Почта</td><td class="reg"><input type="email" name="email"></td></tr>
                    <tr><td class="reg">URI</td><td class="reg"><input type="url" name="url"></td></tr>
                    <tr><td class="reg">IP</td><td class="reg"><input type="txt" name="ip"></td></tr>
                    <tr><td class="reg">Дата рождения</td class="reg"><td class="reg"><input type="date" name="birthday"> </td><td class="reg"><input type="submit" value="Зарегистрироваться" > </td></tr>  
                </form>
            </table>
        </div>
</article>
<?php
$PageController->end_body();
unset($PageController);
?>